// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD88ovrKXbkFGpQqPikqVdnEYay1P76ba0',
    appId: '1:271987412724:web:29b5e2bf32c2e8d05598a1',
    messagingSenderId: '271987412724',
    projectId: 'bazaarbarta-ec1a3',
    authDomain: 'bazaarbarta-ec1a3.firebaseapp.com',
    storageBucket: 'bazaarbarta-ec1a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDct-xCWbeBnzSGhyP0kG5rFEQu8gmQPSU',
    appId: '1:271987412724:android:7e946c031b0766725598a1',
    messagingSenderId: '271987412724',
    projectId: 'bazaarbarta-ec1a3',
    storageBucket: 'bazaarbarta-ec1a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxf2KsLCD9eW0ssenALhenNbIHJKYFz5o',
    appId: '1:271987412724:ios:622817021b01f6d85598a1',
    messagingSenderId: '271987412724',
    projectId: 'bazaarbarta-ec1a3',
    storageBucket: 'bazaarbarta-ec1a3.firebasestorage.app',
    iosBundleId: 'com.example.bazaarbarta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxf2KsLCD9eW0ssenALhenNbIHJKYFz5o',
    appId: '1:271987412724:ios:622817021b01f6d85598a1',
    messagingSenderId: '271987412724',
    projectId: 'bazaarbarta-ec1a3',
    storageBucket: 'bazaarbarta-ec1a3.firebasestorage.app',
    iosBundleId: 'com.example.bazaarbarta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD88ovrKXbkFGpQqPikqVdnEYay1P76ba0',
    appId: '1:271987412724:web:489a2bc80f1ee6375598a1',
    messagingSenderId: '271987412724',
    projectId: 'bazaarbarta-ec1a3',
    authDomain: 'bazaarbarta-ec1a3.firebaseapp.com',
    storageBucket: 'bazaarbarta-ec1a3.firebasestorage.app',
  );

}